
package com.inmarsat.esb.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SAPExchangeServiceEndpoint", targetNamespace = "http://esb.oneitbtp.inmarsat.com/exchange_adapter")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SAPExchangeServiceEndpoint {


    /**
     * 
     * @param in
     * @return
     *     returns com.inmarsat.esb.client.EXCHANGERATERESPONSE
     */
    @WebMethod(action = "http://esb.oneitbtp.inmarsat.com/exchange_adapter/processSAPExchangeRate")
    @WebResult(name = "EXCHANGE_RATE_RESPONSE", targetNamespace = "http://esb.oneitbtp.inmarsat.com/exchange_adapter", partName = "out")
    public EXCHANGERATERESPONSE processSAPExchangeRate(
        @WebParam(name = "EXCHANGE_RATE_REQUEST", targetNamespace = "http://esb.oneitbtp.inmarsat.com/exchange_adapter", partName = "in")
        EXCHANGERATEREQUEST in);

}
